- name: ğŸ» Ensures that DBeaver is using local icon
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Use built-in lineinfile to modify dbeaver icon
      ansible.builtin.lineinfile:
        path: /usr/share/applications/dbeaver-ce.desktop
        regexp: '^Icon.*$'
        line: 'Icon={{ lookup("env", "HOME") }}/Imagens/Ãcones/DBeaver.png'
